// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEEzRm9iBl20Xb0un6CqeG8cqfjA0In_Q',
    appId: '1:68236983986:web:5c6faea8a813b5378493ab',
    messagingSenderId: '68236983986',
    projectId: 'chat-apps-46fc7',
    authDomain: 'chat-apps-46fc7.firebaseapp.com',
    storageBucket: 'chat-apps-46fc7.appspot.com',
    measurementId: 'G-FEGG9WR9EQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdQccnuRePgAEKQk9YiS9_x-hZX1RpmMQ',
    appId: '1:68236983986:android:373fb52eb53e94ae8493ab',
    messagingSenderId: '68236983986',
    projectId: 'chat-apps-46fc7',
    storageBucket: 'chat-apps-46fc7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8xYcA1TyiEBnwGCOZAkVDK68V6kO63O4',
    appId: '1:68236983986:ios:f257af141a44dc168493ab',
    messagingSenderId: '68236983986',
    projectId: 'chat-apps-46fc7',
    storageBucket: 'chat-apps-46fc7.appspot.com',
    iosClientId: '68236983986-qjidsbs2ukn0dnvkuskkrfiqpbi4120b.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8xYcA1TyiEBnwGCOZAkVDK68V6kO63O4',
    appId: '1:68236983986:ios:f257af141a44dc168493ab',
    messagingSenderId: '68236983986',
    projectId: 'chat-apps-46fc7',
    storageBucket: 'chat-apps-46fc7.appspot.com',
    iosClientId: '68236983986-qjidsbs2ukn0dnvkuskkrfiqpbi4120b.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApps',
  );
}
